# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rocketleaguerankUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rocketleagueranks(object):
    def setupUi(self, rocketleagueranks):
        rocketleagueranks.setObjectName("rocketleagueranks")
        rocketleagueranks.resize(680, 498)
        self.centralwidget = QtWidgets.QWidget(rocketleagueranks)
        self.centralwidget.setObjectName("centralwidget")
        self.playerName = QtWidgets.QLineEdit(self.centralwidget)
        self.playerName.setGeometry(QtCore.QRect(160, 20, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.playerName.setFont(font)
        self.playerName.setToolTip("")
        self.playerName.setStatusTip("")
        self.playerName.setInputMask("")
        self.playerName.setText("")
        self.playerName.setMaxLength(15)
        self.playerName.setAlignment(QtCore.Qt.AlignCenter)
        self.playerName.setObjectName("playerName")
        self.labelDivision = QtWidgets.QLabel(self.centralwidget)
        self.labelDivision.setGeometry(QtCore.QRect(20, 137, 261, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelDivision.setFont(font)
        self.labelDivision.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDivision.setObjectName("labelDivision")
        self.labelDivisionRank = QtWidgets.QLabel(self.centralwidget)
        self.labelDivisionRank.setGeometry(QtCore.QRect(20, 190, 261, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelDivisionRank.setFont(font)
        self.labelDivisionRank.setAlignment(QtCore.Qt.AlignCenter)
        self.labelDivisionRank.setObjectName("labelDivisionRank")
        self.favorites = QtWidgets.QComboBox(self.centralwidget)
        self.favorites.setGeometry(QtCore.QRect(160, 71, 151, 20))
        self.favorites.setEditable(False)
        self.favorites.setCurrentText("")
        self.favorites.setObjectName("favorites")
        self.labelRank = QtWidgets.QLabel(self.centralwidget)
        self.labelRank.setGeometry(QtCore.QRect(416, 137, 261, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelRank.setFont(font)
        self.labelRank.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelRank.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelRank.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRank.setObjectName("labelRank")
        self.labelRankRank = QtWidgets.QLabel(self.centralwidget)
        self.labelRankRank.setGeometry(QtCore.QRect(416, 190, 261, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelRankRank.setFont(font)
        self.labelRankRank.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRankRank.setObjectName("labelRankRank")
        self.imageDivision = QtWidgets.QLabel(self.centralwidget)
        self.imageDivision.setGeometry(QtCore.QRect(20, 250, 251, 191))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(140)
        font.setItalic(False)
        self.imageDivision.setFont(font)
        self.imageDivision.setAlignment(QtCore.Qt.AlignCenter)
        self.imageDivision.setObjectName("imageDivision")
        self.imageRank = QtWidgets.QLabel(self.centralwidget)
        self.imageRank.setGeometry(QtCore.QRect(416, 252, 251, 191))
        self.imageRank.setText("")
        self.imageRank.setPixmap(QtGui.QPixmap("unranked.png"))
        self.imageRank.setObjectName("imageRank")
        self.labelError = QtWidgets.QLabel(self.centralwidget)
        self.labelError.setEnabled(True)
        self.labelError.setGeometry(QtCore.QRect(220, 110, 231, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 7, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 7, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 7, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 7, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 7, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 7, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 7, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 105, 105))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 52, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(160, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 7, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 7, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.labelError.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelError.setFont(font)
        self.labelError.setStyleSheet("color: rgb(255, 7, 7);")
        self.labelError.setAlignment(QtCore.Qt.AlignCenter)
        self.labelError.setObjectName("labelError")
        self.comboPlatform = QtWidgets.QComboBox(self.centralwidget)
        self.comboPlatform.setGeometry(QtCore.QRect(430, 70, 101, 22))
        self.comboPlatform.setObjectName("comboPlatform")
        self.comboMode = QtWidgets.QComboBox(self.centralwidget)
        self.comboMode.setGeometry(QtCore.QRect(340, 70, 69, 22))
        self.comboMode.setObjectName("comboMode")
        self.labelCurrentRank = QtWidgets.QLabel(self.centralwidget)
        self.labelCurrentRank.setGeometry(QtCore.QRect(270, 140, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelCurrentRank.setFont(font)
        self.labelCurrentRank.setObjectName("labelCurrentRank")
        self.labelRankRank_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelRankRank_2.setGeometry(QtCore.QRect(250, 190, 181, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelRankRank_2.setFont(font)
        self.labelRankRank_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelRankRank_2.setObjectName("labelRankRank_2")
        rocketleagueranks.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(rocketleagueranks)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 21))
        self.menubar.setObjectName("menubar")
        self.menuAdd_Favorites = QtWidgets.QMenu(self.menubar)
        self.menuAdd_Favorites.setObjectName("menuAdd_Favorites")
        rocketleagueranks.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(rocketleagueranks)
        self.statusbar.setObjectName("statusbar")
        rocketleagueranks.setStatusBar(self.statusbar)
        self.actionAdd = QtWidgets.QAction(rocketleagueranks)
        self.actionAdd.setObjectName("actionAdd")
        self.actionRemove = QtWidgets.QAction(rocketleagueranks)
        self.actionRemove.setObjectName("actionRemove")
        self.menuAdd_Favorites.addAction(self.actionAdd)
        self.menuAdd_Favorites.addAction(self.actionRemove)
        self.menubar.addAction(self.menuAdd_Favorites.menuAction())

        self.retranslateUi(rocketleagueranks)
        QtCore.QMetaObject.connectSlotsByName(rocketleagueranks)

    def retranslateUi(self, rocketleagueranks):
        _translate = QtCore.QCoreApplication.translate
        rocketleagueranks.setWindowTitle(_translate("rocketleagueranks", "Rocket League Ranks"))
        self.playerName.setPlaceholderText(_translate("rocketleagueranks", "Player Name"))
        self.labelDivision.setText(_translate("rocketleagueranks", "Next Divison"))
        self.labelDivisionRank.setText(_translate("rocketleagueranks", "Unranked"))
        self.favorites.setAccessibleName(_translate("rocketleagueranks", "0"))
        self.labelRank.setText(_translate("rocketleagueranks", "Next Rank"))
        self.labelRankRank.setText(_translate("rocketleagueranks", "Unranked"))
        self.imageDivision.setText(_translate("rocketleagueranks", "0"))
        self.labelError.setText(_translate("rocketleagueranks", "TextLabel"))
        self.labelCurrentRank.setText(_translate("rocketleagueranks", "Current MMR"))
        self.labelRankRank_2.setText(_translate("rocketleagueranks", "0"))
        self.menuAdd_Favorites.setTitle(_translate("rocketleagueranks", "Favorites"))
        self.actionAdd.setText(_translate("rocketleagueranks", "Add"))
        self.actionRemove.setText(_translate("rocketleagueranks", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rocketleagueranks = QtWidgets.QMainWindow()
    ui = Ui_rocketleagueranks()
    ui.setupUi(rocketleagueranks)
    rocketleagueranks.show()
    sys.exit(app.exec_())
